# Generated by Django 5.2.6 on 2025-12-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseticket',
            name='signature',
        ),
    ]
