# Generated by Django 5.2.6 on 2026-03-26 17:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_purchaseticket_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseticket',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=23, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseticket',
            name='ticket_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
