# Generated by Django 5.2.6 on 2025-12-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='available_ticket',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='total_ticket',
            field=models.IntegerField(default=1000),
        ),
    ]
