# Generated by Django 5.2.6 on 2025-12-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0002_event_available_ticket_event_total_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_ticket',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_ticket',
            field=models.IntegerField(),
        ),
    ]
