# Generated by Django 5.2.6 on 2025-12-26 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0003_alter_event_available_ticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='Kun din ma k garna')),
                ('task', models.TextField(help_text='Watering, Pesticide')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='agro.crop')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
