# Generated by Django 5.2.6 on 2025-12-27 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0005_usercropadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('spend_date', models.DateField()),
                ('note', models.TextField(blank=True, help_text='e.g., water, food, pesticide', null=True)),
                ('user_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_expenses', to='agro.usercropadd')),
            ],
        ),
    ]
