# Generated by Django 5.2.6 on 2026-01-09 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0006_cropexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Total income from selling')),
                ('quantity', models.FloatField(blank=True, help_text='In kg', null=True)),
                ('sale_date', models.DateField()),
                ('buyer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('user_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_sales', to='agro.usercropadd')),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
    ]
