# Generated by Django 5.2.6 on 2026-02-20 07:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0008_shareknowledge_shareknowledgecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShareKnowledge',
            new_name='CommunityPost',
        ),
        migrations.RenameModel(
            old_name='ShareKnowledgeComment',
            new_name='CommunityPostComment',
        ),
    ]
