# Generated by Django 5.2.6 on 2026-03-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0010_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
