# Generated by Django 5.2.6 on 2026-03-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0011_delete_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
