# Generated by Django 5.2.6 on 2026-04-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0013_event_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
    ]
